version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "3000:3000"  
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mongo-Database
    networks:
      - new-docker-net

  mongo:
    image: mongo:latest 
    ports:
      - "27017:27017" 
    networks:
      - new-docker-net  

networks:
  new-docker-net: 
    driver: bridge 
